# Generated by Django 3.1 on 2023-12-22 10:30

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.datetime
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('city_id', models.AutoField(db_column='city_id', primary_key=True, serialize=False)),
                ('city_name', models.CharField(db_column='city_name', max_length=255)),
                ('generated', models.IntegerField(db_column='generated', default=django.db.models.functions.datetime.Extract(django.db.models.expressions.F('current_timestamp'), 'epoch'))),
            ],
            options={
                'db_table': "'general'.'city_master'",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('co_name', models.CharField(max_length=255)),
                ('generated', models.IntegerField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': "'general'.'client_master'",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('co_id', models.AutoField(db_column='co_id', primary_key=True, serialize=False)),
                ('co_name', models.CharField(db_column='co_name', max_length=255)),
                ('address', models.CharField(db_column='address', max_length=255)),
                ('pincode', models.IntegerField(db_column='pincode')),
                ('generated', models.IntegerField(db_column='generated', default=django.db.models.functions.datetime.Extract(django.db.models.expressions.F('current_timestamp'), 'epoch'))),
            ],
            options={
                'db_table': "'general'.'company_master'",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('country_id', models.AutoField(db_column='country_id', primary_key=True, serialize=False)),
                ('country_name', models.CharField(db_column='country_name', max_length=255)),
                ('generated', models.IntegerField(db_column='generated', default=django.db.models.functions.datetime.Extract(django.db.models.expressions.F('current_timestamp'), 'epoch'))),
            ],
            options={
                'db_table': "'general'.'country_master'",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('state_id', models.AutoField(db_column='state_id', primary_key=True, serialize=False)),
                ('state_name', models.CharField(db_column='state_name', max_length=255)),
                ('generated', models.IntegerField(db_column='generated', default=django.db.models.functions.datetime.Extract(django.db.models.expressions.F('current_timestamp'), 'epoch'))),
            ],
            options={
                'db_table': "'general'.'state_master'",
                'managed': False,
            },
        ),
    ]
