CREATE TABLE general.client_master (
    client_id SERIAL PRIMARY KEY,
    co_name VARCHAR,
    generated INTEGER DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)
);

CREATE TABLE general.company_master(
    co_id SERIAL PRIMARY KEY,
    client_id INTEGER,
    co_name VARCHAR,
    address VARCHAR,
    pincode INTEGER,
    city_id INTEGER,
    country_id INTEGER,
    state_id INTEGER,
    generated INTEGER DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
    FOREIGN KEY (state_id) REFERENCES general.state_master(state_id),
    FOREIGN KEY (country_id) REFERENCES general.country_master(country_id),
    FOREIGN KEY (city_id) REFERENCES general.city_master(city_id)
);

CREATE TABLE general.city_master(
    city_id SERIAL PRIMARY KEY,
    city_name VARCHAR,
    state_id INTEGER,
    generated INTEGER DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
    FOREIGN KEY (state_id) REFERENCES general.state_master(state_id) 
);

CREATE TABLE general.state_master(
    state_id SERIAL PRIMARY KEY,
    state_name VARCHAR,
    country_id INTEGER,
    generated INTEGER DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
    FOREIGN KEY (country_id) REFERENCES general.country_master(country_id)
);

CREATE TABLE general.country_master(
    country_id SERIAL PRIMARY KEY,
    country_name VARCHAR,
    generated INTEGER DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)
)

CREATE TABLE hrm.employees(
    user_id SERIAL PRIMARY KEY,
    client_id INT,
    employee_code INT,
    branch_id INT,
    username VARCHAR(255),
    joining_date DATE,
    left_date DATE,
    working BOOLEAN,
    salary DECIMAL(10, 2),
    pf_no VARCHAR(255),
    esi_no VARCHAR(255),
    pf_limit DECIMAL(10, 2),
    designation VARCHAR(255),
    department VARCHAR(255),
    grad VARCHAR(255),
    dob DATE,
    user_email VARCHAR(255),
    phone VARCHAR(255),
    mobile VARCHAR(255),
    confirmed BOOLEAN,
    password VARCHAR(255),
    transaction_type VARCHAR(255),
    transaction_date DATE,
    desg_id INT,
    webmail_account VARCHAR(255),
    sms_sfa_followups BOOLEAN,
    sales_team_type VARCHAR(255),
    blocked_access BOOLEAN,
    face_reg_done BOOLEAN,
    esop BOOLEAN,
    sys_username VARCHAR(255),
    bank_ins VARCHAR(255),
    rate DECIMAL(10, 2),
    conv_rate DECIMAL(10, 2),
    petrol_amt DECIMAL(10, 2),
    code VARCHAR(255),
    pf_fix BOOLEAN,
    pf_fix_amt DECIMAL(10, 2),
    no_pf BOOLEAN,
    prof_tax DECIMAL(10, 2),
    if_pf_limit DECIMAL(10, 2),
    bank_title VARCHAR(255),
    acc_no VARCHAR(255),
    fathername VARCHAR(255),
    title VARCHAR(255),
    dept_id INT,
    restricted BOOLEAN,
    handle_team BOOLEAN,
    pan_no VARCHAR(255),
    insurance_type VARCHAR(255),
    os VARCHAR(255),
    os_valid_till DATE,
    bank_name VARCHAR(255),
    adhar_card_no VARCHAR(255),
    bank_ifsc_code VARCHAR(255),
    uan_no VARCHAR(255),
    epf_bank_acc VARCHAR(255),
    epf_bank VARCHAR(255),
    epf_bank_ifsc_code VARCHAR(255),
    hired_by VARCHAR(255),
    everyone_ml VARCHAR(255),
    employee_photo VARCHAR(255),
    employee_photo_version VARCHAR(255),
    address VARCHAR(255),
    permanent_address VARCHAR(255),
    prev_pf_acc_no VARCHAR(255),
    prev_pf_uan_no VARCHAR(255),
    prev_pf_withdrawl BOOLEAN,
    gender VARCHAR(255),
    marital_status VARCHAR(255),
    doc_upload_status VARCHAR(255),
    news_paper_allowance DECIMAL(10, 2),
    medical_allowance DECIMAL(10, 2),
    telephone_allowance DECIMAL(10, 2),
    meal_coupons_allowance DECIMAL(10, 2),
    leave_travel_allowance DECIMAL(10, 2),
    mobile_reimbursement DECIMAL(10, 2),
    gpa DECIMAL(10, 2),
    marriage_anniversary DATE,
    prior_work_exp VARCHAR(255),
    mother_name VARCHAR(255),
    spouse_name VARCHAR(255),
    include_in_head_count BOOLEAN,
    valid_from DATE,
    hiring_source VARCHAR(255),
    account_type_handling VARCHAR(255),
    did_numb VARCHAR(255),
    last_drawn_salary DECIMAL(10, 2),
    prev_esic_no VARCHAR(255),
    location_id INT,
    driver_salary DECIMAL(10, 2),
    vertical VARCHAR(255),
    if_intern BOOLEAN,
    lwp BOOLEAN,
    on_commission BOOLEAN,
    reliance_insurance BOOLEAN,
    reliance_insurance_date DATE,
    commission_agent BOOLEAN,
    dsa BOOLEAN,
    dmc_type VARCHAR(255),
    dsa_manager VARCHAR(255),
    maternity_leave BOOLEAN,
    video_meeting_link VARCHAR(255),
    executive_allowance DECIMAL(10, 2),
    highest_qualification1 VARCHAR(255),
    mobile_device_id VARCHAR(255),
    retention_bonus_amount DECIMAL(10, 2),
    performance_incentive_amount DECIMAL(10, 2),
    pli_valid_from DATE,
    retention_bonus_valid_from DATE,
    head_of_department BOOLEAN,
    saturday_off BOOLEAN,
    saturday_wfh BOOLEAN,
    pran_no VARCHAR(255),
    nps_fixed_amount DECIMAL(10, 2),
    nps_percentage DECIMAL(10, 2),
    nps_employer_contribution DECIMAL(10, 2),
    nature_of_exit VARCHAR(255),
    warning_1 VARCHAR(255),
    warning_2 VARCHAR(255),
    car_lease BOOLEAN,
    is_fieldsales BOOLEAN,
    permanent_wfh_from DATE,
    permanent_wfh_to DATE,
    working_mode VARCHAR(255),
    FOREIGN KEY (client_id) REFERENCES general.client_master(client_id)
);

CREATE TABLE general.user_accounts (
    userid                SERIAL PRIMARY KEY,
    username              VARCHAR(50) NOT NULL,
    password              VARCHAR(50),
    title                 VARCHAR(15),
    fname                 VARCHAR(200),
    mname                 VARCHAR(30),
    lname                 VARCHAR(30),
    desg                  VARCHAR(100),
    creation_date         INTEGER,
    creation_time         INTEGER,
    last_visit            INTEGER,
    activation_code       DOUBLE PRECISION,
    auto_registered       BOOLEAN NOT NULL DEFAULT false,
    buy_inquiry           BOOLEAN NOT NULL DEFAULT true,
    sell_inquiry          BOOLEAN NOT NULL DEFAULT true,
    webmail_status        VARCHAR(20) NOT NULL DEFAULT 'NOT REQUESTED',
    account_status        VARCHAR(20) NOT NULL DEFAULT 'INACTIVE',
    section_id            INTEGER,
    heard_from            INTEGER,
    sms_balance           INTEGER,
    last_visit_time       INTEGER,
    id_verified           BOOLEAN NOT NULL DEFAULT true,
    unmoderated_inq       BOOLEAN NOT NULL DEFAULT true,
    tradealert_del_pref   VARCHAR(10),
    terms_accepted        BOOLEAN DEFAULT false,
    inq_orig_pref         INTEGER,
    generated_e           INTEGER DEFAULT EXTRACT(EPOCH FROM NOW())::INTEGER,
    roaming_access        BOOLEAN,
    last_password_change  INTEGER,
    buy_rfis_limit        INTEGER,
    pw_hash               TEXT NOT NULL,
    password_uncr         VARCHAR(15),
    rfis_rate             NUMERIC(5,2),
    avg_rfis_resp_time    NUMERIC(8,2),
    show_rfis_rate        BOOLEAN,
    buyer_feedback        INTEGER,
    show_buyer_feedback   BOOLEAN,
    hide_rfis_rate        BOOLEAN,
    hide_buyer_feedback   BOOLEAN,
    inq_to_all_users      BOOLEAN,
    mark_inquiry_cc       BOOLEAN DEFAULT false,
    user_image            TEXT,
    miss_call_alert       BOOLEAN DEFAULT false,
    merchant_account_id   TEXT,
    google_tnc_accepted   BOOLEAN,
    google_ads_account_id BIGINT,
    is_gmc_link_with_ads  BOOLEAN,
    adhaar_no             VARCHAR(100),
    username_hi           TEXT,
    desg_hi               TEXT
);


CREATE TABLE general.profile_master (
    profile_id SERIAL PRIMARY KEY,
    client_id INT,
    userid_del INTEGER,
    co_name VARCHAR(100),
    address TEXT,
    pincode VARCHAR(20),
    city VARCHAR(100),
    state VARCHAR(80),
    country_code VARCHAR(2),
    phone_no VARCHAR(100),
    fax_no VARCHAR(100),
    email_bak VARCHAR(100),
    website VARCHAR(100),
    co_branches VARCHAR(100),
    estd SMALLINT,
    staff INTEGER,
    prod_exp TEXT,
    prod_imp TEXT,
    prod_manu TEXT,
    prod_serv TEXT,
    ifexporter BOOLEAN NOT NULL DEFAULT false,
    ifimporter BOOLEAN NOT NULL DEFAULT false,
    ifservice BOOLEAN NOT NULL DEFAULT false,
    ifmanu BOOLEAN NOT NULL DEFAULT false,
    bankers VARCHAR(255),
    imp_exp_code VARCHAR(100),
    memb_affil VARCHAR(255),
    std_cert VARCHAR(255),
    area_id INTEGER,
    annual_turn NUMERIC,
    annual_mult NUMERIC,
    annual_currency VARCHAR(5),
    exp_turn NUMERIC,
    exp_mult NUMERIC,
    exp_currency VARCHAR(5),
    imp_turn NUMERIC,
    imp_mult NUMERIC,
    imp_currency VARCHAR(5),
    creation_date INTEGER,
    profile_status VARCHAR(10) NOT NULL DEFAULT 'INCOMPLETE',
    source VARCHAR(20),
    datasource INTEGER,
    company_id INTEGER,
    eyp_list_id INTEGER,
    iid_list_id INTEGER,
    ip_list_id INTEGER,
    catalog_company_id INTEGER,
    extra_attributes BOOLEAN NOT NULL DEFAULT false,
    amount NUMERIC(10, 2) DEFAULT 0.00,
    verified BOOLEAN,
    moderated BOOLEAN,
    junk BOOLEAN,
    non_business BOOLEAN,
    eyp BOOLEAN,
    iid BOOLEAN,
    ip_buyer BOOLEAN,
    ip_seller BOOLEAN,
    service BOOLEAN,
    air_freight BOOLEAN DEFAULT false,
    ocean_freight BOOLEAN DEFAULT false,
    export_freight BOOLEAN DEFAULT true,
    import_freight BOOLEAN DEFAULT true,
    pccode VARCHAR(50),
    pacode VARCHAR(50),
    fccode VARCHAR(50),
    facode VARCHAR(50),
    export_category text[],
    import_category text[],
    serv_category text[],
    manu_category text[],
    last_updated INTEGER,
    entry_by INTEGER,
    last_updated_by INTEGER,
    jr_phone BOOLEAN DEFAULT false,
    jr_address BOOLEAN DEFAULT false,
    jr_co_name BOOLEAN DEFAULT false,
    jr_junk_profile BOOLEAN DEFAULT false,
    jr_no_product BOOLEAN DEFAULT false,
    cr_report BOOLEAN DEFAULT false,
    last_call_key INTEGER,
    not_interested BOOLEAN DEFAULT false,
    spell_mistake BOOLEAN DEFAULT false,
    not_callable BOOLEAN,
    last_verified INTEGER NOT NULL DEFAULT 0,
    has_duplicates BOOLEAN,
    ifdistributor BOOLEAN NOT NULL DEFAULT false,
    prod_distributor TEXT,
    distributor_category text[],
    ifsupplier BOOLEAN NOT NULL DEFAULT false,
    prod_supplier TEXT,
    supplier_category text[],
    iftrader BOOLEAN NOT NULL DEFAULT false,
    prod_trader TEXT,
    trader_category text[],
    directory_listing BOOLEAN,
    product_profile_page VARCHAR(100),
    punchline VARCHAR(200),
    sell_kw_last_modified INTEGER,
    buy_kw_last_modified INTEGER,
    prev_amount NUMERIC(10, 2),
    website_working BOOLEAN,
    mirainform_uniq_id INTEGER,
    website_direct_link BOOLEAN,
    member_since INTEGER,
    number_check_status VARCHAR(20) DEFAULT 'NOT_VERIF',
    number_check_last INTEGER,
    number_check_attempts INTEGER DEFAULT 0,
    number_check_next_check_due INTEGER,
    number_check_result VARCHAR(15),
    co_info TEXT,
    co_logo TEXT,
    number_mask BOOLEAN,
    auto_verified BOOLEAN,
    last_auto_verified INTEGER,
    auto_verification_type VARCHAR(100),
    last_updated_ts INTEGER,
    last_update_comment TEXT,
    cms_production_unit_no INTEGER,
    cms_monthly_prod_capacity VARCHAR,
    cms_no_of_engineers INTEGER,
    cms_no_of_designers INTEGER,
    cms_major_clients VARCHAR,
    cms_capital INTEGER,
    cms_capital_currency VARCHAR(5),
    cms_capital_mul INTEGER,
    cms_export_percentage INTEGER,
    cms_import_percentage INTEGER,
    cms_income_tax_reg_no VARCHAR(50),
    cms_service_tax_no VARCHAR(50),
    cms_central_sales_tax_no VARCHAR(50),
    cms_co_reg_no VARCHAR(50),
    cms_warehousing_facility BOOLEAN,
    cms_orig_equipment_manu BOOLEAN,
    cms_credit_rated BOOLEAN,
    cms_credit_rated_agency INTEGER,
    paypal_id VARCHAR(150),
    customer_value INTEGER,
    business_kws INTEGER[],
    current_contract_amount NUMERIC(10, 2),
    prev_contract_amount NUMERIC(10, 2),
    pincode_id INTEGER,
    gst_no VARCHAR(20),
    pan_no VARCHAR(20),
    business_states INTEGER[],
    exclude_business_cities INTEGER[],
    moderate_inq BOOLEAN,
    dialb2b_inq BOOLEAN,
    primary_business_type VARCHAR(50),
    primary_business_kws TEXT,
    ifwholesaler BOOLEAN NOT NULL DEFAULT false,
    ifretailer BOOLEAN NOT NULL DEFAULT false,
    ifdealer BOOLEAN NOT NULL DEFAULT false,
    iffabricator BOOLEAN NOT NULL DEFAULT false,
    ifproducer BOOLEAN NOT NULL DEFAULT false,
    prod_wholesaler TEXT,
    prod_retailer TEXT,
    prod_dealer TEXT,
    prod_fabricator TEXT,
    prod_producer TEXT,
    ownership_type VARCHAR(100),
    billing_address TEXT,
    billing_city VARCHAR(50),
    billing_state VARCHAR(50),
    billing_pincode INTEGER,
    billing_country_code VARCHAR(2),
    tan_no VARCHAR(20),
    include_business_cities INTEGER[],
    gst_available BOOLEAN,
    dont_show_send_others BOOLEAN,
    trading_brand_name VARCHAR(100),
    manufacturing_brand_name VARCHAR(100),
    distributed_brand_name VARCHAR(100),
    inquiry_preference VARCHAR(100),
    tin_no VARCHAR(50),
    arn_no VARCHAR(50),
    cms_shipment_mode VARCHAR(50),
    cms_production_type VARCHAR(100),
    cms_infrastructure_size VARCHAR(100),
    cms_rewards_recognition TEXT,
    cms_clients_name VARCHAR(100),
    initial_co_name TEXT,
    cms_payment_mode VARCHAR(100),
    cms_niche_market VARCHAR(100),
    cms_tin_no VARCHAR(100),
    restrict_adding_rfis BOOLEAN,
    cin_no VARCHAR(21),
    restrict_automated_rfis BOOLEAN,
    co_logo_img TEXT,
    do_not_automate_rfis BOOLEAN,
    dnd_ivr BOOLEAN,
    dnd_instant_connect BOOLEAN,
    co_name_hi TEXT,
    initial_co_name_hi TEXT,
    vat_no VARCHAR(20),
    address_hi TEXT,
    co_info_hi TEXT,
    state_hi TEXT,
    city_hi TEXT,
    gsp_lead BOOLEAN,
    otp_on_email BOOLEAN,
    include_business_countries TEXT[],
    exclude_business_states INTEGER[],
    international_lead BOOLEAN,
    exclude_business_countries TEXT[],
    fb_automation_flow_controller BOOLEAN,
    FOREIGN KEY (client_id) REFERENCES general.client_master(client_id)
);


CREATE TABLE general.country_master (
    country_code VARCHAR(2) NOT NULL,
    name VARCHAR(100) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    isd_code INTEGER,
    cr_price NUMERIC(10, 2),
    cr_price_old NUMERIC(10, 2),
    continent VARCHAR(50),
    record_type VARCHAR(30) NOT NULL DEFAULT 'COUNTRY',
    im_contact BOOLEAN DEFAULT false,
    sms_allowed BOOLEAN DEFAULT true,
    neighbour_countries TEXT[],
    name_hi TEXT,
    PRIMARY KEY (country_code)
);


CREATE TABLE general.country_states (
    state character varying(80) NOT NULL,
    country_code character varying(2) NOT NULL,
    state_abbrev character varying(10),
    state_id serial NOT NULL,
    zone character varying(100),
    gst_state_code integer,
    alpha_code character varying(3),
    state_hi text,
    for_gst boolean DEFAULT true,
    PRIMARY KEY (state_id),
    FOREIGN KEY (country_code) REFERENCES general.country_master(country_code)
);


CREATE TABLE general.city_master (
    city_id serial NOT NULL,
    city character varying(100) NOT NULL,
    area_code character varying(50),
    branch character varying(80),
    country_code character varying(2) NOT NULL,
    state character varying(80) NOT NULL,
    population numeric,
    admin character varying(1),
    latitude character varying(10),
    longitude character varying(10),
    time_offset double precision,
    audit_created_by integer,
    audit_date_created timestamp with time zone,
    audit_modified_by integer,
    audit_date_modified timestamp with time zone,
    audit_version integer DEFAULT 0,
    audit_id serial NOT NULL,
    city_synonym character varying(100),
    longitude_float double precision,
    latitude_float double precision,
    top_city boolean DEFAULT false,
    search_city boolean NOT NULL DEFAULT false,
    seo_city_id integer,
    covid_zone character varying(50),
    hindi_city character varying(150),
    city_hi text,
    state_hi text,
    city_tier integer,
    PRIMARY KEY (city_id),
    FOREIGN KEY (country_code) REFERENCES general.country_master(country_code)
);

CREATE TABLE general.email_master (
    email_key serial NOT NULL,
    email character varying(250) NOT NULL,
    mail_pref character varying(4) NOT NULL DEFAULT 'HTML'::character varying,
    verification_status character varying(20) NOT NULL DEFAULT 'UNKNOWN'::character varying,
    last_sent integer,
    verified boolean,
    last_verified_on integer DEFAULT general.current_epoch(),
    checked_by character varying(10),
    last_verified_by integer,
    verification_source character varying(20),
    last_logged_in integer,
    PRIMARY KEY (email_key)
);


CREATE TABLE general.mobile_master (
    mobile_key serial NOT NULL,
    mobile character varying(100) NOT NULL,
    mobile_old character varying(100),
    ndnc_status character varying(20),
    ndnc_last_check_date_id integer,
    dnd_preference character varying(50),
    verified boolean,
    last_verified_on integer,
    verified_by integer,
    verification_source character varying(20),
    last_logged_in integer,
    PRIMARY KEY (mobile_key)
);


CREATE TABLE general.account_emails (
    userid integer NOT NULL,
    email_key integer NOT NULL,
    ifdefault boolean NOT NULL,
    uniq_id serial NOT NULL,
    PRIMARY KEY (uniq_id),
    FOREIGN KEY (userid) REFERENCES general.user_accounts(userid),
    FOREIGN KEY (email_key) REFERENCES general.email_master(email_key)
);

CREATE TABLE general.account_mobiles (
    userid integer NOT NULL,
    mobile_key integer NOT NULL,
    ifdefault boolean NOT NULL,
    id serial NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (userid) REFERENCES your_user_table(userid),
    FOREIGN KEY (mobile_key) REFERENCES general.mobile_master(mobile_key)
);


CREATE TABLE general.account_profiles (
    userid integer NOT NULL,
    profile_id integer NOT NULL,
    default_account boolean NOT NULL DEFAULT false,
    uniq_id serial NOT NULL,
    PRIMARY KEY (uniq_id),
    FOREIGN KEY (userid) REFERENCES general.user_accounts(userid),
    FOREIGN KEY (profile_id) REFERENCES general.profile_master(profile_id)
);


CREATE TABLE general.web_category_master (
    category_id SERIAL PRIMARY KEY,
    category_name VARCHAR(180) NOT NULL,
    type VARCHAR(20) NOT NULL DEFAULT 'PRODUCT',
    eypprint_category_id INTEGER,
    iidprint_category_id INTEGER,
    ipprint_category_id INTEGER,
    exp_manu_ind_del INTEGER NOT NULL DEFAULT 0,
    exp_manu_int_del INTEGER NOT NULL DEFAULT 0,
    imp_ind_del INTEGER NOT NULL DEFAULT 0,
    imp_int_del INTEGER NOT NULL DEFAULT 0,
    sp_ind_del INTEGER NOT NULL DEFAULT 0,
    tl_buy_del INTEGER NOT NULL DEFAULT 0,
    tl_sell_del INTEGER NOT NULL DEFAULT 0,
    catalogs_del INTEGER NOT NULL DEFAULT 0,
    keywords_vec TSVECTOR,
    keywords TEXT,
    status VARCHAR(20),
    catalog_gallery INTEGER DEFAULT 0,
    data_count INTEGER,
    multilingual_catalogs INTEGER NOT NULL DEFAULT 0,
    audit_created_by INTEGER,
    audit_date_created TIMESTAMP WITH TIME ZONE,
    audit_modified_by INTEGER,
    audit_date_modified TIMESTAMP WITH TIME ZONE,
    audit_version INTEGER DEFAULT 0,
    parrent_id INTEGER,
    has_content BOOLEAN NOT NULL DEFAULT false,
    pref_exp BOOLEAN NOT NULL DEFAULT true,
    pref_manu BOOLEAN NOT NULL DEFAULT true,
    pref_imp BOOLEAN NOT NULL DEFAULT true,
    seller_del INTEGER NOT NULL DEFAULT 0,
    buyer_del INTEGER NOT NULL DEFAULT 0,
    fp_del INTEGER NOT NULL DEFAULT 0,
    china_suppliers_del INTEGER NOT NULL DEFAULT 0,
    esi_products_del INTEGER NOT NULL DEFAULT 0,
    esi_suppliers_del INTEGER NOT NULL DEFAULT 0,
    automobile_products_del INTEGER NOT NULL DEFAULT 0,
    automobile_suppliers_del INTEGER NOT NULL DEFAULT 0,
    risk_category VARCHAR(30) DEFAULT 'NO_RISK',
    ind_chem_prod_cnt INTEGER,
    b2c BOOLEAN DEFAULT false,
    upper_cat_url VARCHAR(255),
    sale_status VARCHAR(15) NOT NULL DEFAULT 'OPEN',
    gd_dist BOOLEAN DEFAULT false,
    gd_fran BOOLEAN DEFAULT false,
    gd_sales BOOLEAN DEFAULT false,
    exclusive_for_gd BOOLEAN DEFAULT false,
    list_view_type VARCHAR(15),
    es_products_count INTEGER,
    es_company_count INTEGER,
    rel_micro BOOLEAN DEFAULT false,
    name_hi TEXT,
    name_ml TEXT,
    name_bn TEXT,
    name_ta TEXT,
    name_gu TEXT,
    name_te TEXT,
    name_kn TEXT,
    name_mr TEXT,
    name_ar TEXT,
    name_uz TEXT,
    name_vi TEXT,
    name_fr TEXT,
    name_de TEXT,
    name_es TEXT,
    name_it TEXT,
    name_ja TEXT,
    name_ko TEXT,
    name_ru TEXT,
    name_pt TEXT,
    name_zh TEXT,
    name_nl TEXT,
    disclaimer_message TEXT
);
